const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches,clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));const hero=document.querySelector('.hero-image'),track=document.querySelector('.gallery-track'),rail=document.querySelector('.rail'),breakPhoto=document.querySelector('.break-photo'),bar=document.querySelector('.progress');let busy=false;function update(){const y=scrollY,max=document.documentElement.scrollHeight-innerHeight;bar.style.transform=`scaleX(${max?y/max:0})`;if(!reduce){hero.style.transform=`scale(${1.12+clamp(y/innerHeight)*.14}) translateY(${clamp(y/innerHeight)*5}%)`;const r=track.getBoundingClientRect(),p=clamp(-r.top/Math.max(1,r.height-innerHeight));const travel=Math.max(0,rail.scrollWidth-innerWidth+innerWidth*.09);rail.style.transform=`translateX(${-p*travel}px)`;document.querySelector('.track i').style.transform=`scaleX(${p})`;document.querySelector('.counter').textContent=`${String(Math.min(3,Math.floor(p*3)+1)).padStart(2,'0')} / 03`;document.querySelectorAll('.project').forEach((el,i)=>{let dist=Math.abs(p-i/2);el.querySelector('.photo').style.transform=`scale(${1.17-clamp(1-dist)*.12}) translateX(${(i/2-p)*3}%)`});const b=breakPhoto.parentElement.getBoundingClientRect();if(b.top<innerHeight&&b.bottom>0)breakPhoto.style.transform=`scale(${1.16-clamp((innerHeight-b.top)/(b.height+innerHeight))*.16})`;const v=document.querySelector('.vision').getBoundingClientRect();if(v.top<innerHeight&&v.bottom>0)document.querySelector('.vision-line').style.transform=`scaleX(${clamp((innerHeight-v.top)/(v.height+innerHeight))})`}busy=false}addEventListener('scroll',()=>{if(!busy){busy=true;requestAnimationFrame(update)}},{passive:true});addEventListener('resize',update);update();const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('on');obs.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.vision h2,.vision-copy,.end h2,.end-grid p,.big-link').forEach(el=>{el.classList.add('reveal');if(reduce)el.classList.add('on');else obs.observe(el)});

const menuToggle=document.querySelector('.menu-toggle'),mobileNav=document.querySelector('#mobile-nav');
function closeMenu(){mobileNav.hidden=true;menuToggle.setAttribute('aria-expanded','false');menuToggle.setAttribute('aria-label','Abrir menú')}
menuToggle.addEventListener('click',()=>{const opening=mobileNav.hidden;mobileNav.hidden=!opening;menuToggle.setAttribute('aria-expanded',String(opening));menuToggle.setAttribute('aria-label',opening?'Cerrar menú':'Abrir menú')});
mobileNav.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMenu));
addEventListener('keydown',event=>{if(event.key==='Escape'&&!mobileNav.hidden){closeMenu();menuToggle.focus()}});
addEventListener('resize',()=>{if(innerWidth>700)closeMenu()});

document.querySelector('.hero-image')?.classList.add('cover-visual');

;(()=>{const reduced=matchMedia('(prefers-reduced-motion: reduce)');const chapters=[...document.querySelectorAll('.motion-story')];const headings=[...document.querySelectorAll('main section:not(.hero):not(.motion-story) h2')];headings.forEach(el=>el.classList.add('scroll-heading'));let frame=0;const bounded=v=>Math.max(0,Math.min(1,v));function draw(){frame=0;if(reduced.matches)return;chapters.forEach(el=>{const r=el.getBoundingClientRect();if(r.bottom<0||r.top>innerHeight)return;const p=bounded(-r.top/Math.max(1,r.height-innerHeight));el.style.setProperty('--chapter-progress',p);el.style.setProperty('--word-x',`${55-p*145}%`);el.style.setProperty('--turn',`${p*150-35}deg`);el.style.setProperty('--shape-scale',.4+p*1.05);const title=el.querySelector('h2');title.style.translate=`0 ${(p-.5)*-65}px`;el.querySelector('.motion-caption').textContent=String(Math.min(3,Math.floor(p*3)+1)).padStart(2,'0')+' / 03'});headings.forEach(el=>{const r=el.getBoundingClientRect();if(r.bottom<0||r.top>innerHeight)return;const p=bounded((innerHeight-r.top)/(innerHeight*.75));el.style.setProperty('--heading-y',`${(1-p)*65}px`);el.style.setProperty('--heading-opacity',.3+p*.7)})}function schedule(){if(!frame)frame=requestAnimationFrame(draw)}addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);reduced.addEventListener('change',()=>{if(reduced.matches){headings.forEach(el=>{el.style.removeProperty('--heading-y');el.style.removeProperty('--heading-opacity')});chapters.forEach(el=>el.querySelector('h2').style.removeProperty('translate'))}else schedule()});schedule()})();
